apiVersion: v1
kind: Service
metadata:
  name: maybot-control-center
  labels:
    app.kubernetes.io/name: maybot
    app.kubernetes.io/component: control-center
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: maybot
    app.kubernetes.io/component: control-center
  ports:
    - name: http
      port: 8200
      targetPort: http
      protocol: TCP
